{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sonarqube.fullname" . -}}
{{- $svcPort := .Values.service.sonarqube.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.letsencrypt.createClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.letsencrypt.clusterIssuerName }}
    {{- else if .Values.letsencrypt.clusterIssuerName }}
    cert-manager.io/cluster-issuer: {{ .Values.letsencrypt.clusterIssuerName }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
        {{- if .Values.enableWwwRedirect }}
        - "www.{{ .Values.domain }}"
        {{- end }}
      secretName: {{ $fullName }}-tls
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- if .Values.enableWwwRedirect }}
    - host: "www.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end }}

---
{{- if .Values.letsencrypt.createClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.clusterIssuerName }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: {{ .Values.letsencrypt.server }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.clusterIssuerName }}-account-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className | default "traefik" }}
{{- end }}
