apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
