apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarqube
spec:
  type: {{ .Values.service.sonarqube.type }}
  ports:
    - port: {{ .Values.service.sonarqube.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sonarqube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sonarqube
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
    - port: {{ .Values.service.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "sonarqube.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
